---
name: "prerelease"

on:
  workflow_dispatch:
  push:
    tags-ignore:
      - "*.*.*"
    branches:
      - "main"
    paths-ignore:
      - "docs/**"
      - "travis.yml"
      - "README.md"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            target/gringotts-*.*.*-SNAPSHOT.jar
